<?php
function et_twenty_seventeen_getIcons(){
    $arr = array();
    $fontawesome_icons = array(
        array( 'fa-bluetooth' => 'Bluetooth' ),
        array( 'fa-bluetooth-b' => 'Bluetooth-b' ),
        array( 'fa-codiepie' => 'Codiepie' ),
        array( 'fa-credit-card-alt' => 'Credit-card-alt' ),
        array( 'fa-edge' => 'Edge' ),
        array( 'fa-fort-awesome' => 'Fort-awesome' ),
        array( 'fa-hashtag' => 'Hashtag' ),
        array( 'fa-mixcloud' => 'Mixcloud' ),
        array( 'fa-modx' => 'Modx' ),
        array( 'fa-pause-circle' => 'Pause-circle' ),
        array( 'fa-pause-circle-o' => 'Pause-circle-o' ),
        array( 'fa-percent' => 'Percent' ),
        array( 'fa-product-hunt' => 'Product-hunt' ),
        array( 'fa-reddit-alien' => 'Reddit-alien' ),
        array( 'fa-scribd' => 'Scribd' ),
        array( 'fa-shopping-bag' => 'Shopping-bag' ),
        array( 'fa-shopping-basket' => 'Shopping-basket' ),
        array( 'fa-stop-circle' => 'Stop-circle' ),
        array( 'fa-stop-circle-o' => 'Stop-circle-o' ),
        array( 'fa-usb' => 'Usb' ),
        array( 'fa-adjust' => 'Adjust' ),
        array( 'fa-anchor' => 'Anchor' ),
        array( 'fa-archive' => 'Archive' ),
        array( 'fa-area-chart' => 'Area Chart' ),
        array( 'fa-arrows' => 'Arrows' ),
        array( 'fa-arrows-h' => 'Arrows Horizontal' ),
        array( 'fa-arrows-v' => 'Arrows Vertical' ),
        array( 'fa-asterisk' => 'Asterisk' ),
        array( 'fa-at' => 'At' ),
        array( 'fa-balance-scale' => 'Balance Scale' ),
        array( 'fa-ban' => 'Ban' ),
        array( 'fa-bar-chart' => 'Bar Chart (bar-chart-o)' ),
        array( 'fa-barcode' => 'Barcode' ),
        array( 'fa-bars' => 'Bars (navicon, reorder)' ),
        array( 'fa-battery-empty' => 'Battery Empty (battery-0)' ),
        array( 'fa-battery-full' => 'Battery Full (battery-4)' ),
        array( 'fa-battery-half' => 'Battery 1/2 Full (battery-2)' ),
        array( 'fa-battery-quarter' => 'Battery 1/4 Full (battery-1)' ),
        array( 'fa-battery-three-quarters' => 'Battery 3/4 Full (battery-3)' ),
        array( 'fa-bed' => 'Bed (hotel)' ),
        array( 'fa-beer' => 'Beer' ),
        array( 'fa-bell' => 'Bell' ),
        array( 'fa-bell-o' => 'Bell Outlined' ),
        array( 'fa-bell-slash' => 'Bell Slash' ),
        array( 'fa-bell-slash-o' => 'Bell Slash Outlined' ),
        array( 'fa-bicycle' => 'Bicycle' ),
        array( 'fa-binoculars' => 'Binoculars' ),
        array( 'fa-birthday-cake' => 'Birthday Cake' ),
        array( 'fa-bluetooth' => 'Bluetooth' ),
        array( 'fa-bluetooth-b' => 'Bluetooth' ),
        array( 'fa-bolt' => 'Lightning Bolt (flash)' ),
        array( 'fa-bomb' => 'Bomb' ),
        array( 'fa-book' => 'Book' ),
        array( 'fa-bookmark' => 'Bookmark' ),
        array( 'fa-bookmark-o' => 'Bookmark Outlined' ),
        array( 'fa-briefcase' => 'Briefcase' ),
        array( 'fa-bug' => 'Bug' ),
        array( 'fa-building' => 'Building' ),
        array( 'fa-building-o' => 'Building Outlined' ),
        array( 'fa-bullhorn' => 'Bullhorn' ),
        array( 'fa-bullseye' => 'Bullseye' ),
        array( 'fa-bus' => 'Bus' ),
        array( 'fa-calculator' => 'Calculator' ),
        array( 'fa-calendar' => 'Calendar' ),
        array( 'fa-calendar-check-o' => 'Calendar Check Outlined' ),
        array( 'fa-calendar-minus-o' => 'Calendar Minus Outlined' ),
        array( 'fa-calendar-o' => 'Calendar-o' ),
        array( 'fa-calendar-plus-o' => 'Calendar Plus Outlined' ),
        array( 'fa-calendar-times-o' => 'Calendar Times Outlined' ),
        array( 'fa-camera' => 'Camera' ),
        array( 'fa-camera-retro' => 'Camera-retro' ),
        array( 'fa-car' => 'Car (automobile)' ),
        array( 'fa-caret-square-o-down' => 'Caret Square Outlined Down (toggle-down)' ),
        array( 'fa-caret-square-o-left' => 'Caret Square Outlined Left (toggle-left)' ),
        array( 'fa-caret-square-o-right' => 'Caret Square Outlined Right (toggle-right)' ),
        array( 'fa-caret-square-o-up' => 'Caret Square Outlined Up (toggle-up)' ),
        array( 'fa-cart-arrow-down' => 'Shopping Cart Arrow Down' ),
        array( 'fa-cart-plus' => 'Add to Shopping Cart' ),
        array( 'fa-cc' => 'Closed Captions' ),
        array( 'fa-certificate' => 'Certificate' ),
        array( 'fa-check' => 'Check' ),
        array( 'fa-check-circle' => 'Check Circle' ),
        array( 'fa-check-circle-o' => 'Check Circle Outlined' ),
        array( 'fa-check-square' => 'Check Square' ),
        array( 'fa-check-square-o' => 'Check Square Outlined' ),
        array( 'fa-child' => 'Child' ),
        array( 'fa-circle' => 'Circle' ),
        array( 'fa-circle-o' => 'Circle Outlined' ),
        array( 'fa-circle-o-notch' => 'Circle Outlined Notched' ),
        array( 'fa-circle-thin' => 'Circle Outlined Thin' ),
        array( 'fa-clock-o' => 'Clock Outlined' ),
        array( 'fa-clone' => 'Clone' ),
        array( 'fa-cloud' => 'Cloud' ),
        array( 'fa-cloud-download' => 'Cloud Download' ),
        array( 'fa-cloud-upload' => 'Cloud Upload' ),
        array( 'fa-code' => 'Code' ),
        array( 'fa-code-fork' => 'Code-fork' ),
        array( 'fa-coffee' => 'Coffee' ),
        array( 'fa-cog' => 'Cog (gear)' ),
        array( 'fa-cogs' => 'Cogs (gears)' ),
        array( 'fa-comment' => 'Comment' ),
        array( 'fa-comment-o' => 'Comment-o' ),
        array( 'fa-commenting' => 'Commenting' ),
        array( 'fa-commenting-o' => 'Commenting Outlined' ),
        array( 'fa-comments' => 'Comments' ),
        array( 'fa-comments-o' => 'Comments-o' ),
        array( 'fa-compass' => 'Compass' ),
        array( 'fa-copyright' => 'Copyright' ),
        array( 'fa-creative-commons' => 'Creative Commons' ),
        array( 'fa-credit-card' => 'Credit-card' ),
        array( 'fa-credit-card-alt' => 'Credit Card' ),
        array( 'fa-crop' => 'Crop' ),
        array( 'fa-crosshairs' => 'Crosshairs' ),
        array( 'fa-cube' => 'Cube' ),
        array( 'fa-cubes' => 'Cubes' ),
        array( 'fa-cutlery' => 'Cutlery' ),
        array( 'fa-database' => 'Database' ),
        array( 'fa-desktop' => 'Desktop' ),
        array( 'fa-diamond' => 'Diamond' ),
        array( 'fa-dot-circle-o' => 'Dot Circle Outlined' ),
        array( 'fa-download' => 'Download' ),
        array( 'fa-ellipsis-h' => 'Ellipsis Horizontal' ),
        array( 'fa-ellipsis-v' => 'Ellipsis Vertical' ),
        array( 'fa-envelope' => 'Envelope' ),
        array( 'fa-envelope-o' => 'Envelope Outlined' ),
        array( 'fa-envelope-square' => 'Envelope Square' ),
        array( 'fa-eraser' => 'Eraser' ),
        array( 'fa-exchange' => 'Exchange' ),
        array( 'fa-exclamation' => 'Exclamation' ),
        array( 'fa-exclamation-circle' => 'Exclamation Circle' ),
        array( 'fa-exclamation-triangle' => 'Exclamation Triangle (warning)' ),
        array( 'fa-external-link' => 'External Link' ),
        array( 'fa-external-link-square' => 'External Link Square' ),
        array( 'fa-eye' => 'Eye' ),
        array( 'fa-eye-slash' => 'Eye Slash' ),
        array( 'fa-eyedropper' => 'Eyedropper' ),
        array( 'fa-fax' => 'Fax' ),
        array( 'fa-female' => 'Female' ),
        array( 'fa-fighter-jet' => 'Fighter-jet' ),
        array( 'fa-file-archive-o' => 'Archive File Outlined (file-zip-o)' ),
        array( 'fa-file-audio-o' => 'Audio File Outlined (file-sound-o)' ),
        array( 'fa-file-code-o' => 'Code File Outlined' ),
        array( 'fa-file-excel-o' => 'Excel File Outlined' ),
        array( 'fa-file-image-o' => 'Image File Outlined (file-photo-o, file-picture-o)' ),
        array( 'fa-file-pdf-o' => 'PDF File Outlined' ),
        array( 'fa-file-powerpoint-o' => 'Powerpoint File Outlined' ),
        array( 'fa-file-video-o' => 'Video File Outlined (file-movie-o)' ),
        array( 'fa-file-word-o' => 'Word File Outlined' ),
        array( 'fa-film' => 'Film' ),
        array( 'fa-filter' => 'Filter' ),
        array( 'fa-fire' => 'Fire' ),
        array( 'fa-fire-extinguisher' => 'Fire-extinguisher' ),
        array( 'fa-flag' => 'Flag' ),
        array( 'fa-flag-checkered' => 'Flag-checkered' ),
        array( 'fa-flag-o' => 'Flag Outlined' ),
        array( 'fa-flask' => 'Flask' ),
        array( 'fa-folder' => 'Folder' ),
        array( 'fa-folder-o' => 'Folder Outlined' ),
        array( 'fa-folder-open' => 'Folder Open' ),
        array( 'fa-folder-open-o' => 'Folder Open Outlined' ),
        array( 'fa-frown-o' => 'Frown Outlined' ),
        array( 'fa-futbol-o' => 'Futbol Outlined (soccer-ball-o)' ),
        array( 'fa-gamepad' => 'Gamepad' ),
        array( 'fa-gavel' => 'Gavel (legal)' ),
        array( 'fa-gift' => 'Gift' ),
        array( 'fa-glass' => 'Glass' ),
        array( 'fa-globe' => 'Globe' ),
        array( 'fa-graduation-cap' => 'Graduation Cap (mortar-board)' ),
        array( 'fa-hand-lizard-o' => 'Lizard (Hand)' ),
        array( 'fa-hand-paper-o' => 'Paper (Hand) (hand-stop-o)' ),
        array( 'fa-hand-peace-o' => 'Hand Peace' ),
        array( 'fa-hand-pointer-o' => 'Hand Pointer' ),
        array( 'fa-hand-rock-o' => 'Rock (Hand) (hand-grab-o)' ),
        array( 'fa-hand-scissors-o' => 'Scissors (Hand)' ),
        array( 'fa-hand-spock-o' => 'Spock (Hand)' ),
        array( 'fa-hashtag' => 'Hashtag' ),
        array( 'fa-hdd-o' => 'HDD' ),
        array( 'fa-headphones' => 'Headphones' ),
        array( 'fa-heart' => 'Heart' ),
        array( 'fa-heart-o' => 'Heart Outlined' ),
        array( 'fa-heartbeat' => 'Heartbeat' ),
        array( 'fa-history' => 'History' ),
        array( 'fa-home' => 'Home' ),
        array( 'fa-hourglass' => 'Hourglass' ),
        array( 'fa-hourglass-end' => 'Hourglass End (hourglass-3)' ),
        array( 'fa-hourglass-half' => 'Hourglass Half (hourglass-2)' ),
        array( 'fa-hourglass-o' => 'Hourglass Outlined' ),
        array( 'fa-hourglass-start' => 'Hourglass Start (hourglass-1)' ),
        array( 'fa-i-cursor' => 'I Beam Cursor' ),
        array( 'fa-inbox' => 'Inbox' ),
        array( 'fa-industry' => 'Industry' ),
        array( 'fa-info' => 'Info' ),
        array( 'fa-info-circle' => 'Info Circle' ),
        array( 'fa-key' => 'Key' ),
        array( 'fa-keyboard-o' => 'Keyboard Outlined' ),
        array( 'fa-language' => 'Language' ),
        array( 'fa-laptop' => 'Laptop' ),
        array( 'fa-leaf' => 'Leaf' ),
        array( 'fa-lemon-o' => 'Lemon Outlined' ),
        array( 'fa-level-down' => 'Level Down' ),
        array( 'fa-level-up' => 'Level Up' ),
        array( 'fa-life-ring' => 'Life Ring (life-bouy, life-buoy, life-saver, support)' ),
        array( 'fa-lightbulb-o' => 'Lightbulb Outlined' ),
        array( 'fa-line-chart' => 'Line Chart' ),
        array( 'fa-location-arrow' => 'Location-arrow' ),
        array( 'fa-lock' => 'Lock' ),
        array( 'fa-magic' => 'Magic' ),
        array( 'fa-magnet' => 'Magnet' ),
        array( 'fa-male' => 'Male' ),
        array( 'fa-map' => 'Map' ),
        array( 'fa-map-marker' => 'Map-marker' ),
        array( 'fa-map-o' => 'Map Outline' ),
        array( 'fa-map-pin' => 'Map Pin' ),
        array( 'fa-map-signs' => 'Map Signs' ),
        array( 'fa-meh-o' => 'Meh Outlined' ),
        array( 'fa-microphone' => 'Microphone' ),
        array( 'fa-microphone-slash' => 'Microphone Slash' ),
        array( 'fa-minus' => 'Minus' ),
        array( 'fa-minus-circle' => 'Minus Circle' ),
        array( 'fa-minus-square' => 'Minus Square' ),
        array( 'fa-minus-square-o' => 'Minus Square Outlined' ),
        array( 'fa-mobile' => 'Mobile Phone (mobile-phone)' ),
        array( 'fa-money' => 'Money' ),
        array( 'fa-moon-o' => 'Moon Outlined' ),
        array( 'fa-motorcycle' => 'Motorcycle' ),
        array( 'fa-mouse-pointer' => 'Mouse Pointer' ),
        array( 'fa-music' => 'Music' ),
        array( 'fa-newspaper-o' => 'Newspaper Outlined' ),
        array( 'fa-object-group' => 'Object Group' ),
        array( 'fa-object-ungroup' => 'Object Ungroup' ),
        array( 'fa-paint-brush' => 'Paint Brush' ),
        array( 'fa-paper-plane' => 'Paper Plane (send)' ),
        array( 'fa-paper-plane-o' => 'Paper Plane Outlined (send-o)' ),
        array( 'fa-paw' => 'Paw' ),
        array( 'fa-pencil' => 'Pencil' ),
        array( 'fa-pencil-square' => 'Pencil Square' ),
        array( 'fa-pencil-square-o' => 'Pencil Square Outlined (edit)' ),
        array( 'fa-percent' => 'Percent' ),
        array( 'fa-phone' => 'Phone' ),
        array( 'fa-phone-square' => 'Phone Square' ),
        array( 'fa-picture-o' => 'Picture Outlined (photo, image)' ),
        array( 'fa-pie-chart' => 'Pie Chart' ),
        array( 'fa-plane' => 'Plane' ),
        array( 'fa-plug' => 'Plug' ),
        array( 'fa-plus' => 'Plus' ),
        array( 'fa-plus-circle' => 'Plus Circle' ),
        array( 'fa-plus-square' => 'Plus Square' ),
        array( 'fa-plus-square-o' => 'Plus Square Outlined' ),
        array( 'fa-power-off' => 'Power Off' ),
        array( 'fa-print' => 'Print' ),
        array( 'fa-puzzle-piece' => 'Puzzle Piece' ),
        array( 'fa-qrcode' => 'Qrcode' ),
        array( 'fa-question' => 'Question' ),
        array( 'fa-question-circle' => 'Question Circle' ),
        array( 'fa-quote-left' => 'Quote-left' ),
        array( 'fa-quote-right' => 'Quote-right' ),
        array( 'fa-random' => 'Random' ),
        array( 'fa-recycle' => 'Recycle' ),
        array( 'fa-refresh' => 'Refresh' ),
        array( 'fa-registered' => 'Registered Trademark' ),
        array( 'fa-reply' => 'Reply (mail-reply)' ),
        array( 'fa-reply-all' => 'Reply-all (mail-reply-all)' ),
        array( 'fa-retweet' => 'Retweet' ),
        array( 'fa-road' => 'Road' ),
        array( 'fa-rocket' => 'Rocket' ),
        array( 'fa-rss' => 'Rss (feed)' ),
        array( 'fa-rss-square' => 'RSS Square' ),
        array( 'fa-search' => 'Search' ),
        array( 'fa-search-minus' => 'Search Minus' ),
        array( 'fa-search-plus' => 'Search Plus' ),
        array( 'fa-server' => 'Server' ),
        array( 'fa-share' => 'Share (mail-forward)' ),
        array( 'fa-share-alt' => 'Share Alt' ),
        array( 'fa-share-alt-square' => 'Share Alt Square' ),
        array( 'fa-share-square' => 'Share Square' ),
        array( 'fa-share-square-o' => 'Share Square Outlined' ),
        array( 'fa-shield' => 'Shield' ),
        array( 'fa-ship' => 'Ship' ),
        array( 'fa-shopping-bag' => 'Shopping Bag' ),
        array( 'fa-shopping-basket' => 'Shopping Basket' ),
        array( 'fa-shopping-cart' => 'Shopping-cart' ),
        array( 'fa-sign-in' => 'Sign In' ),
        array( 'fa-sign-out' => 'Sign Out' ),
        array( 'fa-signal' => 'Signal' ),
        array( 'fa-sitemap' => 'Sitemap' ),
        array( 'fa-sliders' => 'Sliders' ),
        array( 'fa-smile-o' => 'Smile Outlined' ),
        array( 'fa-sort' => 'Sort (unsorted)' ),
        array( 'fa-sort-alpha-asc' => 'Sort Alpha Ascending' ),
        array( 'fa-sort-alpha-desc' => 'Sort Alpha Descending' ),
        array( 'fa-sort-amount-asc' => 'Sort Amount Ascending' ),
        array( 'fa-sort-amount-desc' => 'Sort Amount Descending' ),
        array( 'fa-sort-asc' => 'Sort Ascending (sort-up)' ),
        array( 'fa-sort-desc' => 'Sort Descending (sort-down)' ),
        array( 'fa-sort-numeric-asc' => 'Sort Numeric Ascending' ),
        array( 'fa-sort-numeric-desc' => 'Sort Numeric Descending' ),
        array( 'fa-space-shuttle' => 'Space Shuttle' ),
        array( 'fa-spinner' => 'Spinner' ),
        array( 'fa-spoon' => 'Spoon' ),
        array( 'fa-square' => 'Square' ),
        array( 'fa-square-o' => 'Square Outlined' ),
        array( 'fa-star' => 'Star' ),
        array( 'fa-star-half' => 'Star-half' ),
        array( 'fa-star-half-o' => 'Star Half Outlined (star-half-empty, star-half-full)' ),
        array( 'fa-star-o' => 'Star Outlined' ),
        array( 'fa-sticky-note' => 'Sticky Note' ),
        array( 'fa-sticky-note-o' => 'Sticky Note Outlined' ),
        array( 'fa-street-view' => 'Street View' ),
        array( 'fa-suitcase' => 'Suitcase' ),
        array( 'fa-sun-o' => 'Sun Outlined' ),
        array( 'fa-tablet' => 'Tablet' ),
        array( 'fa-tachometer' => 'Tachometer (dashboard)' ),
        array( 'fa-tag' => 'Tag' ),
        array( 'fa-tags' => 'Tags' ),
        array( 'fa-tasks' => 'Tasks' ),
        array( 'fa-taxi' => 'Taxi (cab)' ),
        array( 'fa-television' => 'Television (tv)' ),
        array( 'fa-terminal' => 'Terminal' ),
        array( 'fa-thumb-tack' => 'Thumb Tack' ),
        array( 'fa-thumbs-down' => 'Thumbs-down' ),
        array( 'fa-thumbs-o-down' => 'Thumbs Down Outlined' ),
        array( 'fa-thumbs-o-up' => 'Thumbs Up Outlined' ),
        array( 'fa-thumbs-up' => 'Thumbs-up' ),
        array( 'fa-ticket' => 'Ticket' ),
        array( 'fa-times' => 'Times (remove, close)' ),
        array( 'fa-times-circle' => 'Times Circle' ),
        array( 'fa-times-circle-o' => 'Times Circle Outlined' ),
        array( 'fa-tint' => 'Tint' ),
        array( 'fa-toggle-off' => 'Toggle Off' ),
        array( 'fa-toggle-on' => 'Toggle On' ),
        array( 'fa-trademark' => 'Trademark' ),
        array( 'fa-trash' => 'Trash' ),
        array( 'fa-trash-o' => 'Trash Outlined' ),
        array( 'fa-tree' => 'Tree' ),
        array( 'fa-trophy' => 'Trophy' ),
        array( 'fa-truck' => 'Truck' ),
        array( 'fa-tty' => 'TTY' ),
        array( 'fa-umbrella' => 'Umbrella' ),
        array( 'fa-university' => 'University (institution, bank)' ),
        array( 'fa-unlock' => 'Unlock' ),
        array( 'fa-unlock-alt' => 'Unlock Alt' ),
        array( 'fa-upload' => 'Upload' ),
        array( 'fa-user' => 'User' ),
        array( 'fa-user-plus' => 'Add User' ),
        array( 'fa-user-secret' => 'User Secret' ),
        array( 'fa-user-times' => 'Remove User' ),
        array( 'fa-users' => 'Users (group)' ),
        array( 'fa-video-camera' => 'Video Camera' ),
        array( 'fa-volume-down' => 'Volume-down' ),
        array( 'fa-volume-off' => 'Volume-off' ),
        array( 'fa-volume-up' => 'Volume-up' ),
        array( 'fa-wheelchair' => 'Wheelchair' ),
        array( 'fa-wifi' => 'WiFi' ),
        array( 'fa-wrench' => 'Wrench' ),
        array( 'fa-file' => 'File' ),
        array( 'fa-file-archive-o' => 'Archive File Outlined (file-zip-o)' ),
        array( 'fa-file-audio-o' => 'Audio File Outlined (file-sound-o)' ),
        array( 'fa-file-code-o' => 'Code File Outlined' ),
        array( 'fa-file-excel-o' => 'Excel File Outlined' ),
        array( 'fa-file-image-o' => 'Image File Outlined (file-photo-o, file-picture-o)' ),
        array( 'fa-file-o' => 'File Outlined' ),
        array( 'fa-file-pdf-o' => 'PDF File Outlined' ),
        array( 'fa-file-powerpoint-o' => 'Powerpoint File Outlined' ),
        array( 'fa-file-text' => 'File Text' ),
        array( 'fa-file-text-o' => 'File Text Outlined' ),
        array( 'fa-file-video-o' => 'Video File Outlined (file-movie-o)' ),
        array( 'fa-file-word-o' => 'Word File Outlined' ),
        array( 'fa-circle-o-notch' => 'Circle Outlined Notched' ),
        array( 'fa-cog' => 'Cog (gear)' ),
        array( 'fa-refresh' => 'Refresh' ),
        array( 'fa-spinner' => 'Spinner' ),
        array( 'fa-check-square' => 'Check Square' ),
        array( 'fa-check-square-o' => 'Check Square Outlined' ),
        array( 'fa-circle' => 'Circle' ),
        array( 'fa-circle-o' => 'Circle Outlined' ),
        array( 'fa-dot-circle-o' => 'Dot Circle Outlined' ),
        array( 'fa-minus-square' => 'Minus Square' ),
        array( 'fa-minus-square-o' => 'Minus Square Outlined' ),
        array( 'fa-plus-square' => 'Plus Square' ),
        array( 'fa-plus-square-o' => 'Plus Square Outlined' ),
        array( 'fa-square' => 'Square' ),
        array( 'fa-square-o' => 'Square Outlined' ),
        array( 'fa-cc-amex' => 'American Express Credit Card' ),
        array( 'fa-cc-diners-club' => 'Diner\'s Club Credit Card' ),
        array( 'fa-cc-discover' => 'Discover Credit Card' ),
        array( 'fa-cc-jcb' => 'JCB Credit Card' ),
        array( 'fa-cc-mastercard' => 'MasterCard Credit Card' ),
        array( 'fa-cc-paypal' => 'Paypal Credit Card' ),
        array( 'fa-cc-stripe' => 'Stripe Credit Card' ),
        array( 'fa-cc-visa' => 'Visa Credit Card' ),
        array( 'fa-credit-card' => 'Credit-card' ),
        array( 'fa-credit-card-alt' => 'Credit Card' ),
        array( 'fa-google-wallet' => 'Google Wallet' ),
        array( 'fa-paypal' => 'Paypal' ),
        array( 'fa-area-chart' => 'Area Chart' ),
        array( 'fa-bar-chart' => 'Bar Chart (bar-chart-o)' ),
        array( 'fa-line-chart' => 'Line Chart' ),
        array( 'fa-pie-chart' => 'Pie Chart' ),
        array( 'fa-btc' => 'Bitcoin (BTC) (bitcoin)' ),
        array( 'fa-eur' => 'Euro (EUR) (euro)' ),
        array( 'fa-gbp' => 'GBP' ),
        array( 'fa-gg' => 'GG Currency' ),
        array( 'fa-gg-circle' => 'GG Currency Circle' ),
        array( 'fa-ils' => 'Shekel (ILS) (shekel, sheqel)' ),
        array( 'fa-inr' => 'Indian Rupee (INR) (rupee)' ),
        array( 'fa-jpy' => 'Japanese Yen (JPY) (cny, rmb, yen)' ),
        array( 'fa-krw' => 'Korean Won (KRW) (won)' ),
        array( 'fa-money' => 'Money' ),
        array( 'fa-rub' => 'Russian Ruble (RUB) (ruble, rouble)' ),
        array( 'fa-try' => 'Turkish Lira (TRY) (turkish-lira)' ),
        array( 'fa-usd' => 'US Dollar (dollar)' ),
        array( 'fa-align-center' => 'Align-center' ),
        array( 'fa-align-justify' => 'Align-justify' ),
        array( 'fa-align-left' => 'Align-left' ),
        array( 'fa-align-right' => 'Align-right' ),
        array( 'fa-bold' => 'Bold' ),
        array( 'fa-chain-broken' => 'Chain Broken (unlink)' ),
        array( 'fa-clipboard' => 'Clipboard (paste)' ),
        array( 'fa-columns' => 'Columns' ),
        array( 'fa-eraser' => 'Eraser' ),
        array( 'fa-file' => 'File' ),
        array( 'fa-file-o' => 'File Outlined' ),
        array( 'fa-file-text' => 'File Text' ),
        array( 'fa-file-text-o' => 'File Text Outlined' ),
        array( 'fa-files-o' => 'Files Outlined (copy)' ),
        array( 'fa-floppy-o' => 'Floppy Outlined (save)' ),
        array( 'fa-font' => 'Font' ),
        array( 'fa-header' => 'Header' ),
        array( 'fa-indent' => 'Indent' ),
        array( 'fa-italic' => 'Italic' ),
        array( 'fa-link' => 'Link (chain)' ),
        array( 'fa-list' => 'List' ),
        array( 'fa-list-alt' => 'List-alt' ),
        array( 'fa-list-ol' => 'List-ol' ),
        array( 'fa-list-ul' => 'List-ul' ),
        array( 'fa-outdent' => 'Outdent (dedent)' ),
        array( 'fa-paperclip' => 'Paperclip' ),
        array( 'fa-paragraph' => 'Paragraph' ),
        array( 'fa-repeat' => 'Repeat (rotate-right)' ),
        array( 'fa-scissors' => 'Scissors (cut)' ),
        array( 'fa-strikethrough' => 'Strikethrough' ),
        array( 'fa-subscript' => 'Subscript' ),
        array( 'fa-superscript' => 'Superscript' ),
        array( 'fa-table' => 'Table' ),
        array( 'fa-text-height' => 'Text-height' ),
        array( 'fa-text-width' => 'Text-width' ),
        array( 'fa-th' => 'Th' ),
        array( 'fa-th-large' => 'Th-large' ),
        array( 'fa-th-list' => 'Th-list' ),
        array( 'fa-underline' => 'Underline' ),
        array( 'fa-undo' => 'Undo (rotate-left)' ),
        array( 'fa-angle-double-down' => 'Angle Double Down' ),
        array( 'fa-angle-double-left' => 'Angle Double Left' ),
        array( 'fa-angle-double-right' => 'Angle Double Right' ),
        array( 'fa-angle-double-up' => 'Angle Double Up' ),
        array( 'fa-angle-down' => 'Angle-down' ),
        array( 'fa-angle-left' => 'Angle-left' ),
        array( 'fa-angle-right' => 'Angle-right' ),
        array( 'fa-angle-up' => 'Angle-up' ),
        array( 'fa-arrow-circle-down' => 'Arrow Circle Down' ),
        array( 'fa-arrow-circle-left' => 'Arrow Circle Left' ),
        array( 'fa-arrow-circle-o-down' => 'Arrow Circle Outlined Down' ),
        array( 'fa-arrow-circle-o-left' => 'Arrow Circle Outlined Left' ),
        array( 'fa-arrow-circle-o-right' => 'Arrow Circle Outlined Right' ),
        array( 'fa-arrow-circle-o-up' => 'Arrow Circle Outlined Up' ),
        array( 'fa-arrow-circle-right' => 'Arrow Circle Right' ),
        array( 'fa-arrow-circle-up' => 'Arrow Circle Up' ),
        array( 'fa-arrow-down' => 'Arrow-down' ),
        array( 'fa-arrow-left' => 'Arrow-left' ),
        array( 'fa-arrow-right' => 'Arrow-right' ),
        array( 'fa-arrow-up' => 'Arrow-up' ),
        array( 'fa-arrows' => 'Arrows' ),
        array( 'fa-arrows-alt' => 'Arrows Alt' ),
        array( 'fa-arrows-h' => 'Arrows Horizontal' ),
        array( 'fa-arrows-v' => 'Arrows Vertical' ),
        array( 'fa-caret-down' => 'Caret Down' ),
        array( 'fa-caret-left' => 'Caret Left' ),
        array( 'fa-caret-right' => 'Caret Right' ),
        array( 'fa-caret-square-o-down' => 'Caret Square Outlined Down (toggle-down)' ),
        array( 'fa-caret-square-o-left' => 'Caret Square Outlined Left (toggle-left)' ),
        array( 'fa-caret-square-o-right' => 'Caret Square Outlined Right (toggle-right)' ),
        array( 'fa-caret-square-o-up' => 'Caret Square Outlined Up (toggle-up)' ),
        array( 'fa-caret-up' => 'Caret Up' ),
        array( 'fa-chevron-circle-down' => 'Chevron Circle Down' ),
        array( 'fa-chevron-circle-left' => 'Chevron Circle Left' ),
        array( 'fa-chevron-circle-right' => 'Chevron Circle Right' ),
        array( 'fa-chevron-circle-up' => 'Chevron Circle Up' ),
        array( 'fa-chevron-down' => 'Chevron-down' ),
        array( 'fa-chevron-left' => 'Chevron-left' ),
        array( 'fa-chevron-right' => 'Chevron-right' ),
        array( 'fa-chevron-up' => 'Chevron-up' ),
        array( 'fa-exchange' => 'Exchange' ),
        array( 'fa-hand-o-down' => 'Hand Outlined Down' ),
        array( 'fa-hand-o-left' => 'Hand Outlined Left' ),
        array( 'fa-hand-o-right' => 'Hand Outlined Right' ),
        array( 'fa-hand-o-up' => 'Hand Outlined Up' ),
        array( 'fa-long-arrow-down' => 'Long Arrow Down' ),
        array( 'fa-long-arrow-left' => 'Long Arrow Left' ),
        array( 'fa-long-arrow-right' => 'Long Arrow Right' ),
        array( 'fa-long-arrow-up' => 'Long Arrow Up' ),
        array( 'fa-arrows-alt' => 'Arrows Alt' ),
        array( 'fa-backward' => 'Backward' ),
        array( 'fa-compress' => 'Compress' ),
        array( 'fa-eject' => 'Eject' ),
        array( 'fa-expand' => 'Expand' ),
        array( 'fa-fast-backward' => 'Fast-backward' ),
        array( 'fa-fast-forward' => 'Fast-forward' ),
        array( 'fa-forward' => 'Forward' ),
        array( 'fa-pause' => 'Pause' ),
        array( 'fa-pause-circle' => 'Pause Circle' ),
        array( 'fa-pause-circle-o' => 'Pause Circle Outlined' ),
        array( 'fa-play' => 'Play' ),
        array( 'fa-play-circle' => 'Play Circle' ),
        array( 'fa-play-circle-o' => 'Play Circle Outlined' ),
        array( 'fa-random' => 'Random' ),
        array( 'fa-step-backward' => 'Step-backward' ),
        array( 'fa-step-forward' => 'Step-forward' ),
        array( 'fa-stop' => 'Stop' ),
        array( 'fa-stop-circle' => 'Stop Circle' ),
        array( 'fa-stop-circle-o' => 'Stop Circle Outlined' ),
        array( 'fa-youtube-play' => 'YouTube Play' ),
        array( 'fa-ambulance' => 'Ambulance' ),
        array( 'fa-bicycle' => 'Bicycle' ),
        array( 'fa-bus' => 'Bus' ),
        array( 'fa-car' => 'Car (automobile)' ),
        array( 'fa-fighter-jet' => 'Fighter-jet' ),
        array( 'fa-motorcycle' => 'Motorcycle' ),
        array( 'fa-plane' => 'Plane' ),
        array( 'fa-rocket' => 'Rocket' ),
        array( 'fa-ship' => 'Ship' ),
        array( 'fa-space-shuttle' => 'Space Shuttle' ),
        array( 'fa-subway' => 'Subway' ),
        array( 'fa-taxi' => 'Taxi (cab)' ),
        array( 'fa-train' => 'Train' ),
        array( 'fa-truck' => 'Truck' ),
        array( 'fa-wheelchair' => 'Wheelchair' ),
        array( 'fa-hand-lizard-o' => 'Lizard (Hand)' ),
        array( 'fa-hand-o-down' => 'Hand Outlined Down' ),
        array( 'fa-hand-o-left' => 'Hand Outlined Left' ),
        array( 'fa-hand-o-right' => 'Hand Outlined Right' ),
        array( 'fa-hand-o-up' => 'Hand Outlined Up' ),
        array( 'fa-hand-paper-o' => 'Paper (Hand) (hand-stop-o)' ),
        array( 'fa-hand-peace-o' => 'Hand Peace' ),
        array( 'fa-hand-pointer-o' => 'Hand Pointer' ),
        array( 'fa-hand-rock-o' => 'Rock (Hand) (hand-grab-o)' ),
        array( 'fa-hand-scissors-o' => 'Scissors (Hand)' ),
        array( 'fa-hand-spock-o' => 'Spock (Hand)' ),
        array( 'fa-thumbs-down' => 'Thumbs-down' ),
        array( 'fa-thumbs-o-down' => 'Thumbs Down Outlined' ),
        array( 'fa-thumbs-o-up' => 'Thumbs Up Outlined' ),
        array( 'fa-thumbs-up' => 'Thumbs-up' ),
        array( 'fa-genderless' => 'Genderless' ),
        array( 'fa-mars' => 'Mars' ),
        array( 'fa-mars-double' => 'Mars Double' ),
        array( 'fa-mars-stroke' => 'Mars Stroke' ),
        array( 'fa-mars-stroke-h' => 'Mars Stroke Horizontal' ),
        array( 'fa-mars-stroke-v' => 'Mars Stroke Vertical' ),
        array( 'fa-mercury' => 'Mercury' ),
        array( 'fa-neuter' => 'Neuter' ),
        array( 'fa-transgender' => 'Transgender (intersex)' ),
        array( 'fa-transgender-alt' => 'Transgender Alt' ),
        array( 'fa-venus' => 'Venus' ),
        array( 'fa-venus-double' => 'Venus Double' ),
        array( 'fa-venus-mars' => 'Venus Mars' ),
        array( 'fa-500px' => '500px' ),
        array( 'fa-adn' => 'App.net' ),
        array( 'fa-amazon' => 'Amazon' ),
        array( 'fa-android' => 'Android' ),
        array( 'fa-angellist' => 'AngelList' ),
        array( 'fa-apple' => 'Apple' ),
        array( 'fa-behance' => 'Behance' ),
        array( 'fa-behance-square' => 'Behance Square' ),
        array( 'fa-bitbucket' => 'Bitbucket' ),
        array( 'fa-bitbucket-square' => 'Bitbucket Square' ),
        array( 'fa-black-tie' => 'Font Awesome Black Tie' ),
        array( 'fa-bluetooth' => 'Bluetooth' ),
        array( 'fa-bluetooth-b' => 'Bluetooth' ),
        array( 'fa-btc' => 'Bitcoin (BTC) (bitcoin)' ),
        array( 'fa-buysellads' => 'BuySellAds' ),
        array( 'fa-cc-amex' => 'American Express Credit Card' ),
        array( 'fa-cc-diners-club' => 'Diner\'s Club Credit Card' ),
        array( 'fa-cc-discover' => 'Discover Credit Card' ),
        array( 'fa-cc-jcb' => 'JCB Credit Card' ),
        array( 'fa-cc-mastercard' => 'MasterCard Credit Card' ),
        array( 'fa-cc-paypal' => 'Paypal Credit Card' ),
        array( 'fa-cc-stripe' => 'Stripe Credit Card' ),
        array( 'fa-cc-visa' => 'Visa Credit Card' ),
        array( 'fa-chrome' => 'Chrome' ),
        array( 'fa-codepen' => 'Codepen' ),
        array( 'fa-codiepie' => 'Codie Pie' ),
        array( 'fa-connectdevelop' => 'Connect Develop' ),
        array( 'fa-contao' => 'Contao' ),
        array( 'fa-css3' => 'CSS 3 Logo' ),
        array( 'fa-dashcube' => 'DashCube' ),
        array( 'fa-delicious' => 'Delicious Logo' ),
        array( 'fa-deviantart' => 'DeviantART' ),
        array( 'fa-digg' => 'Digg Logo' ),
        array( 'fa-dribbble' => 'Dribbble' ),
        array( 'fa-dropbox' => 'Dropbox' ),
        array( 'fa-drupal' => 'Drupal Logo' ),
        array( 'fa-edge' => 'Edge Browser' ),
        array( 'fa-empire' => 'Galactic Empire (ge)' ),
        array( 'fa-expeditedssl' => 'ExpeditedSSL' ),
        array( 'fa-facebook' => 'Facebook (facebook-f)' ),
        array( 'fa-facebook-official' => 'Facebook Official' ),
        array( 'fa-facebook-square' => 'Facebook Square' ),
        array( 'fa-firefox' => 'Firefox' ),
        array( 'fa-flickr' => 'Flickr' ),
        array( 'fa-fonticons' => 'Fonticons' ),
        array( 'fa-fort-awesome' => 'Fort Awesome' ),
        array( 'fa-forumbee' => 'Forumbee' ),
        array( 'fa-foursquare' => 'Foursquare' ),
        array( 'fa-get-pocket' => 'Get Pocket' ),
        array( 'fa-gg' => 'GG Currency' ),
        array( 'fa-gg-circle' => 'GG Currency Circle' ),
        array( 'fa-git' => 'Git' ),
        array( 'fa-git-square' => 'Git Square' ),
        array( 'fa-github' => 'GitHub' ),
        array( 'fa-github-alt' => 'GitHub Alt' ),
        array( 'fa-github-square' => 'GitHub Square' ),
        array( 'fa-google' => 'Google Logo' ),
        array( 'fa-google-plus' => 'Google Plus' ),
        array( 'fa-google-plus-square' => 'Google Plus Square' ),
        array( 'fa-google-wallet' => 'Google Wallet' ),
        array( 'fa-gittip' => 'Gratipay (Gittip) (gittip)' ),
        array( 'fa-hacker-news' => 'Hacker News (y-combinator-square, yc-square)' ),
        array( 'fa-houzz' => 'Houzz' ),
        array( 'fa-html5' => 'HTML 5 Logo' ),
        array( 'fa-instagram' => 'Instagram' ),
        array( 'fa-internet-explorer' => 'Internet-explorer' ),
        array( 'fa-ioxhost' => 'Ioxhost' ),
        array( 'fa-joomla' => 'Joomla Logo' ),
        array( 'fa-jsfiddle' => 'JsFiddle' ),
        array( 'fa-lastfm' => 'Last.fm' ),
        array( 'fa-lastfm-square' => 'Last.fm Square' ),
        array( 'fa-leanpub' => 'Leanpub' ),
        array( 'fa-linkedin' => 'LinkedIn' ),
        array( 'fa-linkedin-square' => 'LinkedIn Square' ),
        array( 'fa-linux' => 'Linux' ),
        array( 'fa-maxcdn' => 'MaxCDN' ),
        array( 'fa-meanpath' => 'Meanpath' ),
        array( 'fa-medium' => 'Medium' ),
        array( 'fa-mixcloud' => 'Mixcloud' ),
        array( 'fa-modx' => 'MODX' ),
        array( 'fa-odnoklassniki' => 'Odnoklassniki' ),
        array( 'fa-odnoklassniki-square' => 'Odnoklassniki Square' ),
        array( 'fa-opencart' => 'OpenCart' ),
        array( 'fa-openid' => 'OpenID' ),
        array( 'fa-opera' => 'Opera' ),
        array( 'fa-optin-monster' => 'Optin Monster' ),
        array( 'fa-pagelines' => 'Pagelines' ),
        array( 'fa-paypal' => 'Paypal' ),
        array( 'fa-pied-piper' => 'Pied Piper Logo' ),
        array( 'fa-pied-piper-alt' => 'Pied Piper Alternate Logo' ),
        array( 'fa-pinterest' => 'Pinterest' ),
        array( 'fa-pinterest-p' => 'Pinterest P' ),
        array( 'fa-pinterest-square' => 'Pinterest Square' ),
        array( 'fa-product-hunt' => 'Product Hunt' ),
        array( 'fa-qq' => 'QQ' ),
        array( 'fa-rebel' => 'Rebel Alliance (ra)' ),
        array( 'fa-reddit' => 'Reddit Logo' ),
        array( 'fa-reddit-alien' => 'Reddit Alien' ),
        array( 'fa-reddit-square' => 'Reddit Square' ),
        array( 'fa-renren' => 'Renren' ),
        array( 'fa-safari' => 'Safari' ),
        array( 'fa-scribd' => 'Scribd' ),
        array( 'fa-sellsy' => 'Sellsy' ),
        array( 'fa-share-alt' => 'Share Alt' ),
        array( 'fa-share-alt-square' => 'Share Alt Square' ),
        array( 'fa-shirtsinbulk' => 'Shirts in Bulk' ),
        array( 'fa-simplybuilt' => 'SimplyBuilt' ),
        array( 'fa-skyatlas' => 'Skyatlas' ),
        array( 'fa-skype' => 'Skype' ),
        array( 'fa-slack' => 'Slack Logo' ),
        array( 'fa-slideshare' => 'Slideshare' ),
        array( 'fa-soundcloud' => 'SoundCloud' ),
        array( 'fa-spotify' => 'Spotify' ),
        array( 'fa-stack-exchange' => 'Stack Exchange' ),
        array( 'fa-stack-overflow' => 'Stack Overflow' ),
        array( 'fa-steam' => 'Steam' ),
        array( 'fa-steam-square' => 'Steam Square' ),
        array( 'fa-stumbleupon' => 'StumbleUpon Logo' ),
        array( 'fa-stumbleupon-circle' => 'StumbleUpon Circle' ),
        array( 'fa-tencent-weibo' => 'Tencent Weibo' ),
        array( 'fa-trello' => 'Trello' ),
        array( 'fa-tripadvisor' => 'TripAdvisor' ),
        array( 'fa-tumblr' => 'Tumblr' ),
        array( 'fa-tumblr-square' => 'Tumblr Square' ),
        array( 'fa-twitch' => 'Twitch' ),
        array( 'fa-twitter' => 'Twitter' ),
        array( 'fa-twitter-square' => 'Twitter Square' ),
        array( 'fa-usb' => 'USB' ),
        array( 'fa-viacoin' => 'Viacoin' ),
        array( 'fa-vimeo' => 'Vimeo' ),
        array( 'fa-vimeo-square' => 'Vimeo Square' ),
        array( 'fa-vine' => 'Vine' ),
        array( 'fa-vk' => 'VK' ),
        array( 'fa-weibo' => 'Weibo' ),
        array( 'fa-weixin' => 'Weixin (WeChat) (wechat)' ),
        array( 'fa-whatsapp' => 'What\'s App' ),
        array( 'fa-wikipedia-w' => 'Wikipedia W' ),
        array( 'fa-windows' => 'Windows' ),
        array( 'fa-wordpress' => 'WordPress Logo' ),
        array( 'fa-xing' => 'Xing' ),
        array( 'fa-xing-square' => 'Xing Square' ),
        array( 'fa-y-combinator' => 'Y Combinator (yc)' ),
        array( 'fa-yahoo' => 'Yahoo Logo' ),
        array( 'fa-yelp' => 'Yelp' ),
        array( 'fa-youtube' => 'YouTube' ),
        array( 'fa-youtube-play' => 'YouTube Play' ),
        array( 'fa-youtube-square' => 'YouTube Square' ),
        array( 'fa-ambulance' => 'Ambulance' ),
        array( 'fa-h-square' => 'H Square' ),
        array( 'fa-heart' => 'Heart' ),
        array( 'fa-heart-o' => 'Heart Outlined' ),
        array( 'fa-heartbeat' => 'Heartbeat' ),
        array( 'fa-hospital-o' => 'Hospital Outlined' ),
        array( 'fa-medkit' => 'Medkit' ),
        array( 'fa-plus-square' => 'Plus Square' ),
        array( 'fa-stethoscope' => 'Stethoscope' ),
        array( 'fa-user-md' => 'User-md' ),
        array( 'fa-wheelchair' => 'Wheelchair' ),
    );

    foreach ( $fontawesome_icons as $array){
        foreach ($array as $key => $value){
            array_push($arr, $key);
        }
    }

    return $arr;
}

// create icon field
function et_twenty_seventeen_icon_field($settings, $value)
{

    $dependency = vc_generate_dependencies_attributes($settings);
    $param_name = isset($settings['param_name']) ? $settings['param_name'] : '';
    $type = isset($settings['type']) ? $settings['type'] : '';
    $class = isset($settings['class']) ? $settings['class'] : '';
    $icons = array(
        'fa-bookmark',
        'fa-wrench'
    );

    $icons = et_twenty_seventeen_getIcons();

    $output = '<input type="hidden" name="'.$param_name.'" class="wpb_vc_param_value '.$param_name.' '.$type.' '.$class.'" value="'.$value.'" id="trace"/>
				<div class="icon-preview"><i class="fa '.strtolower($value).' fa-2x"></i><label>'.$value.'</label></div>';
    $output .='<input class="search" type="text" placeholder="Search Icon" />';
    $output .='<div id="icon-dropdown" >';
    $output .= '<ul class="icon-list">';
    $n = 1;
    foreach($icons as $icon)
    {
        $selected = ($icon == $value) ? 'class="selected"' : '';
        $id = 'icon-'.$n;
        $output .= '<li '.$selected.' data-ico="'.$icon.'"><i class="fa '.$icon.' fa-2x"></i><label class="icon">'.$icon.'</label></li>';
        $n++;
    }
    $output .='</ul>';
    $output .='</div>';

    $output .= '<script type="text/javascript">
			jQuery(document).ready(function(){
				jQuery(".search").keyup(function(){
			 
					// Retrieve the input field text and reset the count to zero
					var filter = jQuery(this).val(), count = 0;
			 
					// Loop through the icon list
					jQuery(".icon-list li").each(function(){
			 
						// If the list item does not contain the text phrase fade it out
						if (jQuery(this).text().search(new RegExp(filter, "i")) < 0) {
							jQuery(this).fadeOut();
						} else {
							jQuery(this).show();
							count++;
						}
					});
				});
			});

			jQuery("#icon-dropdown li").click(function() {
				jQuery(this).attr("class","selected").siblings().removeAttr("class");
				var icon = jQuery(this).attr("data-ico");
				jQuery("#trace").val(icon);
				jQuery(".icon-preview").html("<i class=\'fa "+icon+" fa-2x\'></i><label>"+icon+"</label>");
			});
	</script>';
    return $output;
}

function et_twenty_seventeen_single_licence()
{
    vc_map( array(
        "name"      => esc_html__( "Single Panel", "et_twenty_seventeen" ),
        "base"      => "single_licence",
        'icon'        => 'single_licence_icon',
        'description' => esc_html__( 'Add a single panel.', 'et_twenty_seventeen' ),
        "wrapper_class" => "clearfix",
        "category" => esc_html__( 'Content', 'et_twenty_seventeen' ),
        "params"    => array(

            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'Title', 'et_twenty_seventeen' ),
                'param_name' => 'title',
                "admin_label" => true,
                'description' => esc_html__( 'Add title.', 'et_twenty_seventeen' ),
            ),
            array(
                "type" => "colorpicker",
                "holder" => "div",
                "heading" => esc_html__("Title Color", "et_twenty_seventeen"),
                "class" => "hide_in_vc_editor",
                "value" => '#222228',
                "param_name" => "title_color",
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'Sub-Title', 'et_twenty_seventeen' ),
                'param_name' => 'subtitle',
                "admin_label" => true,
                'description' => esc_html__( 'Add sub-title.', 'et_twenty_seventeen' ),
            ),
            array(
                "type" => "colorpicker",
                "holder" => "div",
                "heading" => esc_html__("Sub-Title Color", "et_twenty_seventeen"),
                "class" => "hide_in_vc_editor",
                "value" => '#222228',
                "param_name" => "subtitle_color",
            ),
            array(
                "type" => "colorpicker",
                "holder" => "div",
                "heading" => esc_html__("Background Color", "et_twenty_seventeen"),
                "class" => "hide_in_vc_editor",
                "value" => '#222228',
                "param_name" => "bg_color",
            ),
            array(
                'type' => 'checkbox',
                'heading' => esc_html__( 'Add Button?', 'et_twenty_seventeen' ),
                'param_name' => 'layout_link',
                'description' => esc_html__( 'Add a button to the layout.', 'et_twenty_seventeen' ),
            ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__( 'Select Button Style', 'et_twenty_seventeen' ),
                'param_name' => 'style_select',
                'description' => esc_html__( 'Choose a style.', 'et_twenty_seventeen' ),
                "value" => array(
                    'Select Style' => '',
                    'Dark Blue' => 'blue',
                    'Red' => 'red',
                    'Grey' => 'grey'
                )
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'Link Id', 'et_twenty_seventeen' ),
                'param_name' => 'link_id',
                "admin_label" => true,
                'description' => esc_html__( 'Add the quick link ID of the div', 'et_twenty_seventeen' ),
            ),
            array(
                "type" 			=> "icon",
                "class" 		=> "hide_in_vc_editor",
                "admin_label" 	=> true,
                "heading" 		=> "Icon",
                "param_name" 	=> "fa_icon",
                "value" 		=> "fa-bookmark"
            ),
            array(
                "type" => "colorpicker",
                "holder" => "div",
                "heading" => esc_html__("Icon Color", "et_twenty_seventeen"),
                "value" => '#3A3B3D',
                "class" => "hide_in_vc_editor",
                "param_name" => "icon_color",
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'Bullet Item 1', 'et_twenty_seventeen' ),
                'param_name' => 'bullet_1',
                "admin_label" => false,
                'description' => esc_html__( 'Add text for a bullet.', 'et_twenty_seventeen' ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'Bullet Item 2', 'et_twenty_seventeen' ),
                'param_name' => 'bullet_2',
                "admin_label" => false,
                'description' => esc_html__( 'Add text for a bullet.', 'et_twenty_seventeen' ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'Bullet Item 3', 'et_twenty_seventeen' ),
                'param_name' => 'bullet_3',
                "admin_label" => false,
                'description' => esc_html__( 'Add text for a bullet.', 'et_twenty_seventeen' ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'Bullet Item 4', 'et_twenty_seventeen' ),
                'param_name' => 'bullet_4',
                "admin_label" => false,
                'description' => esc_html__( 'Add text for a bullet.', 'et_twenty_seventeen' ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'Bullet Item 5', 'et_twenty_seventeen' ),
                'param_name' => 'bullet_5',
                "admin_label" => false,
                'description' => esc_html__( 'Add text for a bullet.', 'et_twenty_seventeen' ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'Bullet Item 6', 'et_twenty_seventeen' ),
                'param_name' => 'bullet_6',
                "admin_label" => false,
                'description' => esc_html__( 'Add text for a bullet.', 'et_twenty_seventeen' ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'Bullet Item 7', 'et_twenty_seventeen' ),
                'param_name' => 'bullet_7',
                "admin_label" => false,
                'description' => esc_html__( 'Add text for a bullet.', 'et_twenty_seventeen' ),
            ),
            array(
                'param_name'  => 'class',
                'heading'     => esc_html__( 'Class', 'et_twenty_seventeen' ),
                'description' => esc_html__( '(Optional) Enter a unique class name.', 'et_twenty_seventeen' ),
                'type'        => 'textfield',
                "class" => "hide_in_vc_editor",
                'holder'      => 'div'
            )
        )
    ) );

}
et_twenty_seventeen_single_licence();
add_shortcode_param('icon' , 'et_twenty_seventeen_icon_field');

// [single_licence]
add_shortcode( 'single_licence', 'et_twenty_seventeen_single_licence_item_func' );
function et_twenty_seventeen_single_licence_item_func( $atts, $content = null ) { // New function parameter $content is added!
    extract( shortcode_atts( array(
        'class' => '',
        'title' => '',
        'title_color' => '',
        'subtitle' => '',
        'subtitle_color' => '',
        'bg_color' => '',
        'layout_link' => '',
        'style_select' => '',
        'link_id' => '',
        'fa_icon' => '',
        'icon_color' => '',
        'bullet_1' => '',
        'bullet_2' => '',
        'bullet_3' => '',
        'bullet_4' => '',
        'bullet_5' => '',
        'bullet_6' => '',
        'bullet_7' => ''

    ), $atts ) );

    $button_style = '';
    if( $style_select == 'blue'){
        $button_style = 'et-btn-dk-blue';
    } else if( $style_select == 'red'){
        $button_style = 'et-btn-dk-red';
    } else {
        $button_style = 'et-btn-dk-grey';
    }

    // Build Output
    $output = '
        <!-- card item select -->
        <div class="card__item '.esc_attr($class).'" style="background-color:'.esc_attr($bg_color).'">

            <div class="card__item--content">
            
                <h2 style="color:'.esc_attr($title_color).'" >'. wp_kses($title, 'et_twenty_seventeen') .'</h2>';

    $output .= '
                <h3 class="subtitle" style="color:'.esc_attr($subtitle_color).'">'. wp_kses($subtitle, 'et_twenty_seventeen') .'</h3>
                <ul class="card__list">';
    if( strlen($bullet_1) > 0):
        $output .= '
                    <li>
                        <i class="fa '.esc_attr($fa_icon).'" style="color:'.esc_attr($icon_color).'" aria-hidden="true"></i>'. wp_kses( $bullet_1 ,'et_twenty_seventeen') .'
                    </li>';
    endif;
    if( strlen($bullet_2) > 0):
        $output .= '
                    <li>
                        <i class="fa '.esc_attr($fa_icon).'" style="color:'.esc_attr($icon_color).'" aria-hidden="true"></i>'. wp_kses( $bullet_2 ,'et_twenty_seventeen') .'
                    </li>';
    endif;
    if( strlen($bullet_3) > 0):
        $output .= '
                    <li>
                        <i class="fa '.esc_attr($fa_icon).'" style="color:'.esc_attr($icon_color).'" aria-hidden="true"></i>'. wp_kses( $bullet_3 ,'et_twenty_seventeen') .'
                    </li>';
    endif;
    if( strlen($bullet_4) > 0):
        $output .= '
                    <li>
                        <i class="fa '.esc_attr($fa_icon).'" style="color:'.esc_attr($icon_color).'" aria-hidden="true"></i>'. wp_kses( $bullet_4 ,'et_twenty_seventeen') .'
                    </li>';
    endif;
    if( strlen($bullet_5) > 0):
        $output .= '
                    <li>
                        <i class="fa '.esc_attr($fa_icon).'" style="color:'.esc_attr($icon_color).'" aria-hidden="true"></i>'. wp_kses( $bullet_5 ,'et_twenty_seventeen') .'
                    </li>';
    endif;
    if( strlen($bullet_6) > 0):
        $output .= '
                    <li>
                        <i class="fa '.esc_attr($fa_icon).'" style="color:'.esc_attr($icon_color).'" aria-hidden="true"></i>'. wp_kses( $bullet_6 ,'et_twenty_seventeen') .'
                    </li>';
    endif;
    if( strlen($bullet_7) > 0):
        $output .= '
                    <li>
                        <i class="fa '.esc_attr($fa_icon).'" style="color:'.esc_attr($icon_color).'" aria-hidden="true"></i>'. wp_kses( $bullet_7 ,'et_twenty_seventeen') .'
                    </li>';
    endif;
        $output .= '
                </ul>
        ';

    if($layout_link == "true"):
        $output .= '
            <a href="#'.esc_attr($link_id).'" target="_self" class="et-btn-round '.esc_attr($button_style).'">
                        <span class="eltdf-btn-text">'.esc_html__('Read more', 'et_twenty_seventeen').'</span>
            </a>
        ';

    endif;

        $output .= '   
            </div>

        </div>
    ';

    return $output;
}