<?php
if( function_exists('acf_add_local_field_group') ):

    acf_add_local_field_group(array (
        'key' => 'group_57000e9894af9',
        'title' => 'Courses',
        'fields' => array (
            array (
                'default_value' => '',
                'placeholder' => '',
                'key' => 'field_57000ea70c5de',
                'label' => 'Course Url',
                'name' => 'course_url',
                'type' => 'url',
                'instructions' => 'Add Course URL',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
            ),
            array (
                'sub_fields' => array (
                    array (
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'key' => 'field_57017e9dd9220',
                        'label' => 'Tag',
                        'name' => 'tag',
                        'type' => 'text',
                        'instructions' => 'Enter tag name',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'readonly' => 0,
                        'disabled' => 0,
                    ),
                ),
                'min' => 0,
                'max' => 0,
                'layout' => 'table',
                'button_label' => 'Add Row',
                'collapsed' => 'field_57017e9dd9220',
                'key' => 'field_57017e8ed921f',
                'label' => 'Course Tags',
                'name' => 'course_tags',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'courses',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
    ));

    acf_add_local_field_group(array (
        'key' => 'group_566cbd5a68564',
        'title' => 'Main Featured Product',
        'fields' => array (
            array (
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'key' => 'field_5664db7a56eb4',
                'label' => 'Feature Headline',
                'name' => 'feature_headline',
                'type' => 'text',
                'instructions' => 'Product Headline',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'formatting' => 'none',
                'readonly' => 0,
                'disabled' => 0,
            ),
            array (
                'default_value' => '',
                'new_lines' => '',
                'maxlength' => '',
                'placeholder' => '',
                'rows' => 4,
                'key' => 'field_5664dba956eb5',
                'label' => 'Feature Text',
                'name' => 'feature_text',
                'type' => 'textarea',
                'instructions' => 'Short Description about product',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'readonly' => 0,
                'disabled' => 0,
            ),
            array (
                'placement' => 'top',
                'endpoint' => 0,
                'key' => 'field_5665399093993',
                'label' => 'Price',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
            ),
            array (
                'default_value' => 0,
                'message' => '',
                'ui' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
                'key' => 'field_56653683ded8b',
                'label' => 'Pay What you want?',
                'name' => 'feature_pwyw',
                'type' => 'true_false',
                'instructions' => 'Check this item if it has a set price',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
            ),
            array (
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'key' => 'field_5664dcc0b094f',
                'label' => 'Feature Price',
                'name' => 'feature_price',
                'type' => 'text',
                'instructions' => 'Enter Product Price',
                'required' => 1,
                'conditional_logic' => array (
                    array (
                        array (
                            'field' => 'field_56653683ded8b',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'formatting' => 'none',
                'readonly' => 0,
                'disabled' => 0,
            ),
            array (
                'placement' => 'top',
                'endpoint' => 0,
                'key' => 'field_566539d37e642',
                'label' => 'Color',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
            ),
            array (
                'multiple' => 0,
                'allow_null' => 0,
                'choices' => array (
                    'white' => 'white',
                    'black' => 'black',
                ),
                'default_value' => array (
                ),
                'ui' => 0,
                'ajax' => 0,
                'placeholder' => '',
                'return_format' => 'value',
                'key' => 'field_566536fa0d9f1',
                'label' => 'Price Color',
                'name' => 'feature_price_color',
                'type' => 'select',
                'instructions' => 'Choose the background color',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'disabled' => 0,
                'readonly' => 0,
            ),
            array (
                'placement' => 'top',
                'endpoint' => 0,
                'key' => 'field_56653a24764e2',
                'label' => 'Gumroad Link',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
            ),
            array (
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => 'https://',
                'prepend' => '',
                'append' => '',
                'key' => 'field_5664dd73ea2e0',
                'label' => 'Feature Gumroad Link',
                'name' => 'feature_gumroad_link',
                'type' => 'text',
                'instructions' => 'Add Gumroad Url here',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'formatting' => 'html',
                'readonly' => 0,
                'disabled' => 0,
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'page',
                    'operator' => '==',
                    'value' => '2618',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => array (
            0 => 'the_content',
        ),
        'active' => 1,
        'description' => '',
    ));

    acf_add_local_field_group(array (
        'key' => 'group_566cbd5a8ba9e',
        'title' => 'Product',
        'fields' => array (
            array (
                'default_value' => 0,
                'message' => '',
                'ui' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
                'key' => 'field_5677db1b0fddc',
                'label' => 'Shortcode',
                'name' => 'shortcode',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
            ),
            array (
                'tabs' => 'all',
                'toolbar' => 'basic',
                'media_upload' => 0,
                'default_value' => '',
                'delay' => 0,
                'key' => 'field_5663d9734a5a5',
                'label' => 'ShortCode Link',
                'name' => 'shortcode_link',
                'type' => 'wysiwyg',
                'instructions' => 'Add Gumroad shortcode here',
                'required' => 1,
                'conditional_logic' => array (
                    array (
                        array (
                            'field' => 'field_5677db1b0fddc',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
            ),
            array (
                'placement' => 'top',
                'endpoint' => 0,
                'key' => 'field_56766c46e4695',
                'label' => 'Price Settings',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
            ),
            array (
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'key' => 'field_5663db3a2f60b',
                'label' => 'Price',
                'name' => 'price',
                'type' => 'text',
                'instructions' => 'Add Product Price',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'formatting' => 'none',
                'readonly' => 0,
                'disabled' => 0,
            ),
            array (
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'key' => 'field_5663e021d258b',
                'label' => 'gumroad link',
                'name' => 'gumroad_link',
                'type' => 'text',
                'instructions' => 'gumroad url',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'formatting' => 'none',
                'readonly' => 0,
                'disabled' => 0,
            ),
            array (
                'default_value' => 0,
                'message' => '',
                'ui' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
                'key' => 'field_56766c5ae4696',
                'label' => 'Extended Price',
                'name' => 'has_extended_price',
                'type' => 'true_false',
                'instructions' => 'Check if there is an extended license',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
            ),
            array (
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'key' => 'field_56766bf5e4694',
                'label' => 'Extended license price',
                'name' => 'extended_price',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array (
                    array (
                        array (
                            'field' => 'field_56766c5ae4696',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'readonly' => 0,
                'disabled' => 0,
            ),
            array (
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'key' => 'field_56766fb859625',
                'label' => 'Extended License Url',
                'name' => 'extended_license_url',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array (
                    array (
                        array (
                            'field' => 'field_56766c5ae4696',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'readonly' => 0,
                'disabled' => 0,
            ),
            array (
                'placement' => 'top',
                'endpoint' => 0,
                'key' => 'field_56766ca1e4697',
                'label' => 'Extras',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
            ),
            array (
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => 'Add youtube link if available',
                'prepend' => '',
                'append' => '',
                'key' => 'field_5664a0d3f49e0',
                'label' => 'Youtube link',
                'name' => 'youtube_link',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'formatting' => 'none',
                'readonly' => 0,
                'disabled' => 0,
            ),
            array (
                'default_value' => 0,
                'message' => '',
                'ui' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
                'key' => 'field_56a71c1ca318b',
                'label' => 'Enable Font Preview',
                'name' => 'has_font_preview',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
            ),
            array (
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'key' => 'field_56a71c62a318c',
                'label' => 'Font Name',
                'name' => 'font_name',
                'type' => 'text',
                'instructions' => 'This is the name of the css file. Example: tuesday.css - the name would be tuesday.',
                'required' => 0,
                'conditional_logic' => array (
                    array (
                        array (
                            'field' => 'field_56a71c1ca318b',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'readonly' => 0,
                'disabled' => 0,
            ),
            array (
                'sub_fields' => array (
                    array (
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'key' => 'field_57c2370acc38b',
                        'label' => 'Style',
                        'name' => 'style',
                        'type' => 'text',
                        'instructions' => 'Add Style',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'readonly' => 0,
                        'disabled' => 0,
                    ),
                ),
                'min' => 0,
                'max' => 0,
                'layout' => 'table',
                'button_label' => 'Add Style',
                'collapsed' => 'field_57c2370acc38b',
                'key' => 'field_57c236f8cc38a',
                'label' => 'Font Styles',
                'name' => 'font_styles',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'product',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'seamless',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
    ));

    acf_add_local_field_group(array (
        'key' => 'group_566cbd5a9aa4b',
        'title' => 'Sub-Feature Right',
        'fields' => array (
            array (
                'return_format' => 'array',
                'preview_size' => 'full',
                'library' => 'all',
                'min_width' => 0,
                'min_height' => 0,
                'min_size' => 0,
                'max_width' => 0,
                'max_height' => 0,
                'max_size' => 0,
                'mime_types' => '',
                'key' => 'field_56650147287a1',
                'label' => 'Sub Right Image',
                'name' => 'sub_right_image',
                'type' => 'image',
                'instructions' => 'Add Image here',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
            ),
            array (
                'placement' => 'top',
                'endpoint' => 0,
                'key' => 'field_5665c7ad8bbe5',
                'label' => 'Price',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
            ),
            array (
                'default_value' => 0,
                'message' => '',
                'ui' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
                'key' => 'field_5665c7d4b7b88',
                'label' => 'Pay what you want?',
                'name' => 'sub_right_pwyw',
                'type' => 'true_false',
                'instructions' => 'Check this item if it has a set price',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
            ),
            array (
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'key' => 'field_56650179287a2',
                'label' => 'Sub Right Price',
                'name' => 'sub_right_price',
                'type' => 'text',
                'instructions' => 'Add Price here',
                'required' => 1,
                'conditional_logic' => array (
                    array (
                        array (
                            'field' => 'field_5665c7d4b7b88',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'formatting' => 'none',
                'readonly' => 0,
                'disabled' => 0,
            ),
            array (
                'placement' => 'top',
                'endpoint' => 0,
                'key' => 'field_5665c811b7b89',
                'label' => 'Color',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
            ),
            array (
                'multiple' => 0,
                'allow_null' => 0,
                'choices' => array (
                    'white' => 'white',
                    'black' => 'black',
                ),
                'default_value' => array (
                ),
                'ui' => 0,
                'ajax' => 0,
                'placeholder' => '',
                'return_format' => 'value',
                'key' => 'field_5665c81db7b8a',
                'label' => 'Choose Color',
                'name' => 'sub_right_color',
                'type' => 'select',
                'instructions' => 'Chose the color of the banner background',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'disabled' => 0,
                'readonly' => 0,
            ),
            array (
                'placement' => 'top',
                'endpoint' => 0,
                'key' => 'field_5665c85ab7b8b',
                'label' => 'Gumroad Link',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
            ),
            array (
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'key' => 'field_56650634130fd',
                'label' => 'Sub Right Link',
                'name' => 'sub_right_link',
                'type' => 'text',
                'instructions' => 'Add Gumroad link',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'formatting' => 'none',
                'readonly' => 0,
                'disabled' => 0,
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'page',
                    'operator' => '==',
                    'value' => '2618',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
        'modified' => 1449987265,
        'local' => 'json',
    ));

    acf_add_local_field_group(array (
        'key' => 'group_566cbd5ab9de9',
        'title' => 'Sub-Feature Left',
        'fields' => array (
            array (
                'return_format' => 'array',
                'preview_size' => 'full',
                'library' => 'all',
                'min_width' => 0,
                'min_height' => 0,
                'min_size' => 0,
                'max_width' => 0,
                'max_height' => 0,
                'max_size' => 0,
                'mime_types' => '',
                'key' => 'field_56652791688c4',
                'label' => 'Sub left image',
                'name' => 'sub_left_image',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
            ),
            array (
                'placement' => 'top',
                'endpoint' => 0,
                'key' => 'field_5665cbd0b6020',
                'label' => 'Price',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
            ),
            array (
                'default_value' => 0,
                'message' => '',
                'ui' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
                'key' => 'field_5665cbf5b6021',
                'label' => 'Pay what you want?',
                'name' => 'sub_left_pwyw',
                'type' => 'true_false',
                'instructions' => 'Check this item if it has a set price',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
            ),
            array (
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'key' => 'field_566527be688c5',
                'label' => 'Sub left Price',
                'name' => 'sub_left_price',
                'type' => 'text',
                'instructions' => 'Product Price',
                'required' => 1,
                'conditional_logic' => array (
                    array (
                        array (
                            'field' => 'field_5665cbf5b6021',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'formatting' => 'none',
                'readonly' => 0,
                'disabled' => 0,
            ),
            array (
                'placement' => 'top',
                'endpoint' => 0,
                'key' => 'field_5665cc22b6022',
                'label' => 'Color',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
            ),
            array (
                'multiple' => 0,
                'allow_null' => 0,
                'choices' => array (
                    'white' => 'white',
                    'black' => 'black',
                ),
                'default_value' => array (
                ),
                'ui' => 0,
                'ajax' => 0,
                'placeholder' => '',
                'return_format' => 'value',
                'key' => 'field_5665cc35b6023',
                'label' => 'Choose Color',
                'name' => 'sub_left_color',
                'type' => 'select',
                'instructions' => 'Chose the color of the banner background',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'disabled' => 0,
                'readonly' => 0,
            ),
            array (
                'placement' => 'top',
                'endpoint' => 0,
                'key' => 'field_5665cc5cb6024',
                'label' => 'Gumroad Link',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
            ),
            array (
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => 'https://',
                'prepend' => '',
                'append' => '',
                'key' => 'field_566527e2688c6',
                'label' => 'Gumroad Url',
                'name' => 'sub_left_link',
                'type' => 'text',
                'instructions' => 'Gumroad Url',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'formatting' => 'none',
                'readonly' => 0,
                'disabled' => 0,
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'page',
                    'operator' => '==',
                    'value' => '2618',
                ),
            ),
        ),
        'menu_order' => 1,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
    ));

    acf_add_local_field_group(array (
        'key' => 'group_56922e077a0cf',
        'title' => 'License Info Description',
        'fields' => array (
            array (
                'tabs' => 'all',
                'toolbar' => 'full',
                'media_upload' => 0,
                'default_value' => '',
                'delay' => 0,
                'key' => 'field_56922e3d4a2fd',
                'label' => 'Standard Content',
                'name' => 'standard_content',
                'type' => 'wysiwyg',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
            ),
            array (
                'tabs' => 'all',
                'toolbar' => 'full',
                'media_upload' => 1,
                'default_value' => '',
                'delay' => 0,
                'key' => 'field_56922e954a2fe',
                'label' => 'Extended Content',
                'name' => 'extended',
                'type' => 'wysiwyg',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'page-product.php',
                ),
            ),
            array (
                array (
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'page-product-react.php',
                ),
            ),
            array (
                array (
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'full-width.php',
                ),
            ),
        ),
        'menu_order' => 3,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
    ));

endif;